services:
  frontend:
    build: ./frontend 
    ports:
      - "5173:5173"  
    volumes:
      - ./frontend:/app
      - /app/node_modules      
    environment:
      - CHOKIDAR_USEPOLI=true
  db:
    image: mysql:8.0
    healthcheck:
      test: "exit 0"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: issue_tracking_system

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - .:/go/src/api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: 127.0.0.1"
      DB_USER: root
      DB_PASSWORD: pass
      DB_NAME: issue_tracking_system
    links:
      - db
    depends_on:
      - db

volumes:
  db_data:
