version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to the frontend Dockerfile
    ports:
      - "80:80"  # Expose frontend on port 80
    networks:
      - app-network

  backend:
    build:
      context: ./ # Path to the backend Dockerfile
    ports:
      - "8080:8080"  # Expose backend API on port 8080
    networks:
      - app-network
    depends_on:
      - frontend  # Ensures backend starts after frontend

networks:
  app-network:
    driver: bridge
