-- MySQL Script generated by MySQL Workbench
-- Fri 02 May 2025 08:41:18 PM BST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema issue_tracking_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema issue_tracking_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `issue_tracking_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `issue_tracking_system` ;

-- -----------------------------------------------------
-- Table `issue_tracking_system`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_tracking_system`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `issue_tracking_system`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_tracking_system`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_key` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `project_lead` INT UNSIGNED NULL DEFAULT NULL,
  `issue_count` INT NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `wip_limit` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `project_key` (`project_key` ASC) VISIBLE,
  INDEX `project_lead` (`project_lead` ASC) VISIBLE,
  CONSTRAINT `projects_ibfk_1`
    FOREIGN KEY (`project_lead`)
    REFERENCES `issue_tracking_system`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `issue_tracking_system`.`sprints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_tracking_system`.`sprints` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `project_key` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `project_key` (`project_key` ASC) VISIBLE,
  CONSTRAINT `sprints_ibfk_1`
    FOREIGN KEY (`project_key`)
    REFERENCES `issue_tracking_system`.`projects` (`project_key`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `issue_tracking_system`.`issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_tracking_system`.`issues` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NOT NULL,
  `summary` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `project_key` VARCHAR(255) NOT NULL,
  `reporter` VARCHAR(255) NOT NULL,
  `assignee` VARCHAR(255) NOT NULL,
  `status` ENUM('open', 'in_progress', 'resolved') NOT NULL DEFAULT 'open',
  `issueType` ENUM('bug', 'task', 'story') NOT NULL DEFAULT 'task',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sprint_id` INT UNSIGNED NULL DEFAULT NULL,
  `started_at` TIMESTAMP NULL DEFAULT NULL,
  `finished_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key` (`key` ASC) VISIBLE,
  INDEX `project_key` (`project_key` ASC) VISIBLE,
  INDEX `fk_issues_sprint` (`sprint_id` ASC) VISIBLE,
  CONSTRAINT `fk_issues_sprint`
    FOREIGN KEY (`sprint_id`)
    REFERENCES `issue_tracking_system`.`sprints` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `issues_ibfk_1`
    FOREIGN KEY (`project_key`)
    REFERENCES `issue_tracking_system`.`projects` (`project_key`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `issue_tracking_system`.`project_assignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_tracking_system`.`project_assignments` (
  `project_id` INT NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `role` VARCHAR(255) NULL DEFAULT 'member',
  `assigned_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`project_id`, `user_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `project_assignments_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `issue_tracking_system`.`projects` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `project_assignments_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `issue_tracking_system`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `issue_tracking_system`.`scopes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_tracking_system`.`scopes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `issue_tracking_system`.`project_scope`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_tracking_system`.`project_scope` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_key` VARCHAR(255) NOT NULL,
  `scope_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `project_key` (`project_key` ASC) VISIBLE,
  INDEX `scope_id` (`scope_id` ASC) VISIBLE,
  CONSTRAINT `project_scope_ibfk_1`
    FOREIGN KEY (`project_key`)
    REFERENCES `issue_tracking_system`.`projects` (`project_key`)
    ON DELETE CASCADE,
  CONSTRAINT `project_scope_ibfk_2`
    FOREIGN KEY (`scope_id`)
    REFERENCES `issue_tracking_system`.`scopes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `issue_tracking_system`.`schema_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_tracking_system`.`schema_migrations` (
  `version` BIGINT NOT NULL,
  `dirty` TINYINT(1) NOT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `issue_tracking_system`.`sprint_issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_tracking_system`.`sprint_issues` (
  `issue_id` INT UNSIGNED NOT NULL,
  `sprint_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`issue_id`, `sprint_id`),
  INDEX `sprint_id` (`sprint_id` ASC) VISIBLE,
  CONSTRAINT `sprint_issues_ibfk_1`
    FOREIGN KEY (`issue_id`)
    REFERENCES `issue_tracking_system`.`issues` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `sprint_issues_ibfk_2`
    FOREIGN KEY (`sprint_id`)
    REFERENCES `issue_tracking_system`.`sprints` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `issue_tracking_system`.`standups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_tracking_system`.`standups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_key` VARCHAR(255) NOT NULL,
  `start_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_time` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `project_key` (`project_key` ASC) VISIBLE,
  CONSTRAINT `standups_ibfk_1`
    FOREIGN KEY (`project_key`)
    REFERENCES `issue_tracking_system`.`projects` (`project_key`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
